spring:
#  DB config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/<name-of-DB>
    username: <username-goes-here>
    password: <password-goes-here>
    initialization-mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#  API endpoints
  data:
    rest:
      base-path: /api/v1

#path for Swagger-UI docs
springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html

  api-docs:
    path: /api/v1/api-docs